import type { CoreOptions } from '@d-zero/a11y-check-core';

export type A11yCheckAxeOptions = CoreOptions & {
	readonly lang?: string;
};

export type Explanation = {
	main: string;
	help: string;
};

export type AxeRuleId =
	| 'area-alt'
	| 'aria-allowed-attr'
	| 'aria-braille-equivalent'
	| 'aria-command-name'
	| 'aria-conditional-attr'
	| 'aria-deprecated-role'
	| 'aria-hidden-body'
	| 'aria-hidden-focus'
	| 'aria-input-field-name'
	| 'aria-meter-name'
	| 'aria-progressbar-name'
	| 'aria-prohibited-attr'
	| 'aria-required-attr'
	| 'aria-required-children'
	| 'aria-required-parent'
	| 'aria-roles'
	| 'aria-toggle-field-name'
	| 'aria-tooltip-name'
	| 'aria-valid-attr-value'
	| 'aria-valid-attr'
	| 'blink'
	| 'button-name'
	| 'bypass'
	| 'color-contrast'
	| 'definition-list'
	| 'dlitem' // cspell:disable-line
	| 'document-title'
	| 'duplicate-id-aria'
	| 'form-field-multiple-labels'
	| 'frame-focusable-content'
	| 'frame-title-unique'
	| 'frame-title'
	| 'html-has-lang'
	| 'html-lang-valid'
	| 'html-xml-lang-mismatch'
	| 'image-alt'
	| 'input-button-name'
	| 'input-image-alt'
	| 'label'
	| 'link-in-text-block'
	| 'link-name'
	| 'list'
	| 'listitem'
	| 'marquee'
	| 'meta-refresh'
	| 'meta-viewport'
	| 'nested-interactive'
	| 'no-autoplay-audio'
	| 'object-alt'
	| 'role-img-alt'
	| 'scrollable-region-focusable'
	| 'select-name'
	| 'server-side-image-map'
	| 'summary-name'
	| 'svg-img-alt'
	| 'td-headers-attr'
	| 'th-has-data-cells'
	| 'valid-lang'
	| 'video-caption'
	| 'autocomplete-valid'
	| 'avoid-inline-spacing'
	| 'target-size'
	| 'accesskeys'
	| 'aria-allowed-role'
	| 'aria-dialog-name'
	| 'aria-text'
	| 'aria-treeitem-name'
	| 'empty-heading'
	| 'empty-table-header'
	| 'frame-tested'
	| 'heading-order'
	| 'image-redundant-alt'
	| 'label-title-only'
	| 'landmark-banner-is-top-level'
	| 'landmark-complementary-is-top-level'
	| 'landmark-contentinfo-is-top-level'
	| 'landmark-main-is-top-level'
	| 'landmark-no-duplicate-banner'
	| 'landmark-no-duplicate-contentinfo'
	| 'landmark-no-duplicate-main'
	| 'landmark-one-main'
	| 'landmark-unique'
	| 'meta-viewport-large'
	| 'page-has-heading-one'
	| 'presentation-role-conflict'
	| 'region'
	| 'scope-attr-valid'
	| 'skip-link'
	| 'tabindex'
	| 'table-duplicate-name'
	| 'color-contrast-enhanced'
	| 'identical-links-same-purpose'
	| 'meta-refresh-no-exceptions'
	| 'css-orientation-lock'
	| 'focus-order-semantics'
	| 'hidden-content'
	| 'label-content-name-mismatch'
	| 'p-as-heading'
	| 'table-fake-caption'
	| 'td-has-header'
	| 'aria-roledescription'
	| 'audio-caption'
	| 'duplicate-id-active'
	| 'duplicate-id';
